### ISSUE TITLE
Seems to be broken with GitLab 12.10

### ISSUE THREAD

**Issue by JacobDB** [HCESrl/gitlab-standard-labels#6]
Generated a few labels, but then errored with the following:

```
No default board found. Please visit the board page in order to trigger the default GitLab board creation. Hopefully one day this is gonna be fixed by the GitLab team...
Creating all labels in repository weblinx/vernon-hills-park-district
Error: Request failed with status code 409
    at setStandardLabels (/home/jacob/.nvm/versions/node/v12.16.3/lib/node_modules/gitlab-standard-labels/labels/index.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Could be because I already had a couple of labels set up manually, but in the past this has always worked fine (it would error, but still make the rest of the labels).

**Comment by fsavina** [comment]
@JacobDB hi! As the messages says "Please visit the board page in order to trigger the default GitLab board creation." then try again

**Comment by JacobDB** [comment]
I mean, I've seen that before but it's never been an actual issue. Just generated the boards, and the same error's still occurring.

```
Creating all labels in repository weblinx/vernon-hills-park-district
Error: Request failed with status code 409
    at setStandardLabels (/home/jacob/.nvm/versions/node/v12.16.3/lib/node_modules/gitlab-standard-labels/labels/index.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Config is below, screenshot of generated labels is below that.

```
[
    {
        "name": "Priority: Critical",
        "color": "#ee0701",
        "board": false,
        "priority": 1
    },
    {
        "name": "Priority: High",
        "color": "#d93f0b",
        "board": false,
        "priority": 2
    },
    {
        "name": "Priority: Medium",
        "color": "#fbca04",
        "board": false,
        "priority": 3
    },
    {
        "name": "Priority: Low",
        "color": "#0e8a16",
        "board": false,
        "priority": 4
    },
    {
        "name": "Status: Abandoned",
        "color": "#000000",
        "board": false
    },
    {
        "name": "Status: Available",
        "color": "#c2e0c6",
        "board": false
    },
    {
        "name": "Status: Blocked",
        "color": "#ee0701",
        "board": false
    },
    {
        "name": "Status: Completed",
        "color": "#0e8a16",
        "board": false
    },
    {
        "name": "Status: Feedback Needed",
        "color": "#fbca04",
        "board": false
    },
    {
        "name": "Status: In Progress",
        "color": "#cccccc",
        "board": false
    },
    {
        "name": "Status: On Hold",
        "color": "#e99695",
        "board": false
    },
    {
        "name": "Status: Proposal",
        "color": "#d4c5f9",
        "board": false
    },
    {
        "name": "Status: Review Needed",
        "color": "#fbca04",
        "board": false
    },
    {
        "name": "Type: Bug",
        "color": "#ee0701",
        "board": false
    },
    {
        "name": "Type: Documentation",
        "color": "#5319e7",
        "board": false
    },
    {
        "name": "Type: Enhancement",
        "color": "#1d76db",
        "board": false
    },
    {
        "name": "Type: Maintenance",
        "color": "#fbca04",
        "board": false
    },
    {
        "name": "Type: Question",
        "color": "#cc317c",
        "board": false
    },
    {
        "name": "duplicate",
        "color": "#ededed",
        "board": false
    },
    {
        "name": "greenkeeper",
        "color": "#ededed",
        "board": false
    },
    {
        "name": "starter",
        "color": "#ffc0cb",
        "board": false
    }
]
```

![image](https://user-images.githubusercontent.com/1123997/82074075-d1ad8d80-969f-11ea-8760-c124913accfd.png)
